import jsPDF from 'jspdf'

export const exportToPDF = (assessment) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const maxWidth = pageWidth - (margin * 2)
  let yPosition = margin

  // Helper function to add text with automatic page breaks
  const addText = (text, fontSize, fontStyle = 'normal', color = [0, 0, 0]) => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', fontStyle)
    doc.setTextColor(...color)

    const lines = doc.splitTextToSize(text, maxWidth)
    lines.forEach(line => {
      if (yPosition > pageHeight - margin) {
        doc.addPage()
        yPosition = margin
      }
      doc.text(line, margin, yPosition)
      yPosition += fontSize * 0.5
    })
    yPosition += 3
  }

  const addSpace = (space = 5) => {
    yPosition += space
  }

  // Title
  addText('Supply Chain Assessment Questions', 18, 'bold', [0, 82, 204])
  addSpace(3)

  // Metadata Section
  addText('Assessment Details', 14, 'bold')
  addSpace(2)
  addText(`Learning Objective: ${assessment.metadata.learningObjective}`, 10)
  addText(`Bloom's Taxonomy Level: ${capitalizeFirst(assessment.metadata.bloomsLevel)}`, 10)
  addText(`Context: ${assessment.metadata.context}`, 10)
  addText(`Difficulty: ${capitalizeFirst(assessment.metadata.difficulty)}`, 10)
  addText(`Generated: ${assessment.metadata.generatedDate}`, 10)
  addSpace(8)

  // Divider line
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  addSpace(8)

  // Questions Section
  assessment.questions.forEach((question, index) => {
    // Question header
    addText(`Question ${index + 1} - ${question.type}`, 12, 'bold', [0, 82, 204])
    addSpace(3)

    // Question text
    addText(question.question, 10, 'normal')
    addSpace(5)

    // Options for MCQ
    if (question.type === 'Multiple Choice') {
      question.options.forEach((option, optIndex) => {
        const optionLetter = String.fromCharCode(65 + optIndex)
        const correctIndicator = option.isCorrect ? ' ✓ (CORRECT)' : ''
        const textColor = option.isCorrect ? [0, 135, 90] : [0, 0, 0]
        const fontWeight = option.isCorrect ? 'bold' : 'normal'

        addText(`${optionLetter}. ${option.text}${correctIndicator}`, 9, fontWeight, textColor)
        addSpace(2)
      })
      addSpace(3)
    }

    // Rubric/Answer Key
    addText(question.type === 'Multiple Choice' ? 'Answer Key' : 'Scoring Rubric', 11, 'bold', [90, 90, 90])
    addSpace(2)

    if (question.type === 'Multiple Choice') {
      addText(`Correct Answer: ${question.rubric.correctAnswer}`, 9)
      addSpace(2)
      addText(`Explanation: ${question.rubric.explanation}`, 9)
      addSpace(2)
      addText(`Point Value: ${question.rubric.pointValue} point`, 9)
    } else {
      addText(`Criteria: ${question.rubric.criteria}`, 9)
      addSpace(3)
      addText(`Scoring Guide (Maximum: ${question.rubric.maxPoints} points):`, 9, 'bold')
      addSpace(2)
      addText(`• Exemplary: ${question.rubric.scoringGuide.exemplary}`, 9)
      addText(`• Proficient: ${question.rubric.scoringGuide.proficient}`, 9)
      addText(`• Developing: ${question.rubric.scoringGuide.developing}`, 9)
      addText(`• Unsatisfactory: ${question.rubric.scoringGuide.unsatisfactory}`, 9)
    }

    addSpace(8)

    // Divider between questions
    if (index < assessment.questions.length - 1) {
      doc.setDrawColor(220, 220, 220)
      doc.line(margin, yPosition, pageWidth - margin, yPosition)
      addSpace(8)
    }
  })

  // Footer on last page
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${totalPages} | Generated by Assessment Question Generator`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
  }

  // Save the PDF
  const filename = `Assessment_${assessment.metadata.context.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`
  doc.save(filename)
}

// Helper function to capitalize first letter
const capitalizeFirst = (str) => {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
